=== davidqian91/startfromhere/database/hw4/movie.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xs:element name="movie">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="row" minOccurs ="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Movie_ID" type="xs:string"/>
                            <xs:element name="Title" type="xs:string"/>
                            <xs:element name="Director" type="xs:string"/>
                            <xs:element name="Writer" type="xs:string" minOccurs ="1" maxOccurs="unbounded"/>
                            <xs:element name="Genre" type="xs:string" minOccurs ="1" maxOccurs="unbounded"/>
                            <xs:element name="Release_Date" type="xs:date"/>
                            <xs:element name="Runtime" type="xs:integer" minOccurs="0" maxOccurs="1"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== davidqian91/startfromhere/database/hw4/schema.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="movie.xsd">
    <record>
       <Movie_ID>M1</Movie_ID>
       <Title>The Shawshank Redemption</Title>
       <Director>Frank Darabont</Director>
       <Writer>Stephen King, Frank Darabont</Writer>
       <Genre>Crime Drama</Genre>
       <Release_Date>1994-10-14</Release_Date>
       <Runtime>142</Runtime>
    </record>
</movie>

=== davidqian91/startfromhere/database/hw4/output.xml
<movie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="movie.xsd">
	<row>
		<Movie_ID>M1</Movie_ID>
		<Title>The Shawshank Redemption</Title>
		<Director>Frank Darabont</Director>
		<Writer>Frank Darabont</Writer>
		<Writer>Stephen King</Writer>
		<Genre>Crime Drama</Genre>
		<Release_Date>1994-10-14</Release_Date>
		<Runtime>142</Runtime>
	</row>
	<row>
		<Movie_ID>M2</Movie_ID>
		<Title>The Godfather</Title>
		<Director>Francis Ford Coppola</Director>
		<Writer>Francis Ford Coppola</Writer>
		<Writer>Mario Puzo</Writer>
		<Genre>Crime Drama</Genre>
		<Release_Date>1948-03-24</Release_Date>
		<Runtime>195</Runtime>
	</row>
	<row>
		<Movie_ID>M3</Movie_ID>
		<Title>Inception</Title>
		<Director>Christopher Nolan</Director>
		<Writer>Christopher Nolan</Writer>
		<Genre>Action Mystery Sci-Fi Thriller</Genre>
		<Release_Date>2008-10-19</Release_Date>
		<Runtime>148</Runtime>
	</row>
	<row>
		<Movie_ID>M4</Movie_ID>
		<Title>Pulp Fiction</Title>
		<Director>Quentin Tarantino</Director>
		<Writer>Roger Avary</Writer>
		<Writer>Quentin Tarantino</Writer>
		<Genre>Crime Drama</Genre>
		<Release_Date>1994-10-14</Release_Date>
		<Runtime>154</Runtime>
	</row>
	<row>
		<Movie_ID>M5</Movie_ID>
		<Title>Schindler's List</Title>
		<Director>Steven Spielberg</Director>
		<Writer>Steven Zaillian</Writer>
		<Writer>Thomas Keneally</Writer>
		<Genre>Biography Drama History</Genre>
		<Release_Date>1994-02-04</Release_Date>
		<Runtime>195</Runtime>
	</row>
	<row>
		<Movie_ID>M6</Movie_ID>
		<Title>The Dark Knight</Title>
		<Director>Christopher Nolan</Director>
		<Writer>Christopher Nolan</Writer>
		<Writer>Jonathan Nolan</Writer>
		<Genre>Action Crime Drama</Genre>
		<Release_Date>2008-10-18</Release_Date>
		<Runtime>152</Runtime>
	</row>
	<row>
		<Movie_ID>M7</Movie_ID>
		<Title>One Flew Over the Cuckoo's Nest</Title>
		<Director>Milos Forman</Director>
		<Writer>Bo Goldman</Writer>
		<Writer>Lawrence Hauben</Writer>
		<Genre>Drama</Genre>
		<Release_Date>1975-11-21</Release_Date>
		<Runtime>133</Runtime>
	</row>
	<row>
		<Movie_ID>M8</Movie_ID>
		<Title>The Lord of the Rings: The Two Towers</Title>
		<Director>Peter Jackson</Director>
		<Writer>Fran Walsh</Writer>
		<Writer>J.R.R. Tolkien</Writer>
		<Genre>Adventure Fantasy</Genre>
		<Release_Date>2002-12-18</Release_Date>
		<Runtime>179</Runtime>
	</row>
	<row>
		<Movie_ID>M9</Movie_ID>
		<Title>Goodfellas</Title>
		<Director>Martin Scorsese</Director>
		<Writer>Nicholas Pileggi</Writer>
		<Genre>Biography Crime Drama</Genre>
		<Release_Date>1990-09-21</Release_Date>
		<Runtime>146</Runtime>
	</row>
	<row>
		<Movie_ID>M10</Movie_ID>
		<Title>The Matrix</Title>
		<Director>Andy Wachowski, Lana Wachowski</Director>
		<Writer>Lana Wachowski</Writer>
		<Writer>Andy Wachowski</Writer>
		<Genre>Action Sci-Fi</Genre>
		<Release_Date>1990-03-31</Release_Date>
		<Runtime>136</Runtime>
	</row>
	<row>
		<Movie_ID>M11</Movie_ID>
		<Title>Inglourious Basterds</Title>
		<Director>Quentin Tarantino, Eli Roth</Director>
		<Writer>Quentin Tarantino</Writer>
		<Genre>Adventure Drama War</Genre>
		<Release_Date>2008-08-21</Release_Date>
		<Runtime>153</Runtime>
	</row>
	<row>
		<Movie_ID>M12</Movie_ID>
		<Title>Toy Story</Title>
		<Director>John Lasseter</Director>
		<Writer>Pete Docter</Writer>
		<Writer>John Lasseter</Writer>
		<Genre>Animation Adventure Comedy Family Fantasy</Genre>
		<Release_Date>1995-11-22</Release_Date>
		<Runtime>81</Runtime>
	</row>
	<row>
		<Movie_ID>M13</Movie_ID>
		<Title>The Treasure of the Sierra Madre</Title>
		<Director>John Huston</Director>
		<Writer>B. Traven</Writer>
		<Writer>John Huston</Writer>
		<Genre>Action Adventure Drama</Genre>
		<Release_Date>1948-01-24</Release_Date>
		<Runtime>126</Runtime>
	</row>
	<row>
		<Movie_ID>M14</Movie_ID>
		<Title>Indiana Jones and the Last Crusade</Title>
		<Director>Steven Spielberg</Director>
		<Writer>George Lucas</Writer>
		<Writer>Jeffrey Boam</Writer>
		<Genre>Action Adventure</Genre>
		<Release_Date>1995-05-24</Release_Date>
		<Runtime>127</Runtime>
	</row>
	<row>
		<Movie_ID>M15</Movie_ID>
		<Title>Some Like It Hot</Title>
		<Director>Billy Wilder</Director>
		<Writer>I.A.L. Diamond</Writer>
		<Writer>Billy Wilder</Writer>
		<Genre>Comedy</Genre>
		<Release_Date>1948-03-29</Release_Date>
		<Runtime>120</Runtime>
	</row>
</movie>

=== davidqian91/startfromhere/database/hw4/untitled folder/movie.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movie xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="movie.xsd">
	<row>
		<Movie_ID>M1</Movie_ID>
		<Title>The Shawshank Redemption</Title>
		<Director>Frank Darabont</Director>
		<Writer>Stephen King, Frank Darabont</Writer>
		<Genre>Crime Drama</Genre>
		<Release_Date>1994-10-14</Release_Date>
		<Runtime>142</Runtime>
	</row>
	<row>
		<Movie_ID>M2</Movie_ID>
		<Title>The Godfather</Title>
		<Director>Francis Ford Coppola</Director>
		<Writer>Mario Puzo, Francis Ford Coppola</Writer>
		<Genre>Crime Drama</Genre>
		<Release_Date>1948-03-24</Release_Date>
		<Runtime>195</Runtime>
	</row>
	<row>
		<Movie_ID>M3</Movie_ID>
		<Title>Inception</Title>
		<Director>Christopher Nolan</Director>
		<Writer>Christopher Nolan</Writer>
		<Genre>Action Mystery Sci-Fi Thriller</Genre>
		<Release_Date>2008-10-19</Release_Date>
		<Runtime>148</Runtime>
	</row>
	<row>
		<Movie_ID>M4</Movie_ID>
		<Title>Pulp Fiction</Title>
		<Director>Quentin Tarantino</Director>
		<Writer>Quentin Tarantino, Roger Avary</Writer>
		<Genre>Crime Drama</Genre>
		<Release_Date>1994-10-14</Release_Date>
		<Runtime>154</Runtime>
	</row>
	<row>
		<Movie_ID>M5</Movie_ID>
		<Title>Schindler's List</Title>
		<Director>Steven Spielberg</Director>
		<Writer>Thomas Keneally, Steven Zaillian</Writer>
		<Genre>Biography Drama History</Genre>
		<Release_Date>1994-02-04</Release_Date>
		<Runtime>195</Runtime>
	</row>
	<row>
		<Movie_ID>M6</Movie_ID>
		<Title>The Dark Knight</Title>
		<Director>Christopher Nolan</Director>
		<Writer>Jonathan Nolan, Christopher Nolan</Writer>
		<Genre>Action Crime Drama</Genre>
		<Release_Date>2008-10-18</Release_Date>
		<Runtime>152</Runtime>
	</row>
	<row>
		<Movie_ID>M7</Movie_ID>
		<Title>One Flew Over the Cuckoo's Nest</Title>
		<Director>Milos Forman</Director>
		<Writer>Lawrence Hauben, Bo Goldman</Writer>
		<Genre>Drama</Genre>
		<Release_Date>1975-11-21</Release_Date>
		<Runtime>133</Runtime>
	</row>
	<row>
		<Movie_ID>M8</Movie_ID>
		<Title>The Lord of the Rings: The Two Towers</Title>
		<Director>Peter Jackson</Director>
		<Writer>J.R.R. Tolkien, Fran Walsh</Writer>
		<Genre>Adventure Fantasy</Genre>
		<Release_Date>2002-12-18</Release_Date>
		<Runtime>179</Runtime>
	</row>
	<row>
		<Movie_ID>M9</Movie_ID>
		<Title>Goodfellas</Title>
		<Director>Martin Scorsese</Director>
		<Writer>Nicholas Pileggi</Writer>
		<Genre>Biography Crime Drama</Genre>
		<Release_Date>1990-09-21</Release_Date>
		<Runtime>146</Runtime>
	</row>
	<row>
		<Movie_ID>M10</Movie_ID>
		<Title>The Matrix</Title>
		<Director>Andy Wachowski, Lana Wachowski</Director>
		<Writer>Andy Wachowski, Lana Wachowski</Writer>
		<Genre>Action Sci-Fi</Genre>
		<Release_Date>1990-03-31</Release_Date>
		<Runtime>136</Runtime>
	</row>
	<row>
		<Movie_ID>M11</Movie_ID>
		<Title>Inglourious Basterds</Title>
		<Director>Quentin Tarantino, Eli Roth</Director>
		<Writer>Quentin Tarantino</Writer>
		<Genre>Adventure Drama War</Genre>
		<Release_Date>2008-08-21</Release_Date>
		<Runtime>153</Runtime>
	</row>
	<row>
		<Movie_ID>M12</Movie_ID>
		<Title>Toy Story</Title>
		<Director>John Lasseter</Director>
		<Writer>John Lasseter, Pete Docter</Writer>
		<Genre>Animation Adventure Comedy Family Fantasy</Genre>
		<Release_Date>1995-11-22</Release_Date>
		<Runtime>81</Runtime>
	</row>
	<row>
		<Movie_ID>M13</Movie_ID>
		<Title>The Treasure of the Sierra Madre</Title>
		<Director>John Huston</Director>
		<Writer>John Huston, B. Traven</Writer>
		<Genre>Action Adventure Drama</Genre>
		<Release_Date>1948-01-24</Release_Date>
		<Runtime>126</Runtime>
	</row>
	<row>
		<Movie_ID>M14</Movie_ID>
		<Title>Indiana Jones and the Last Crusade</Title>
		<Director>Steven Spielberg</Director>
		<Writer>Jeffrey Boam, George Lucas</Writer>
		<Genre>Action Adventure</Genre>
		<Release_Date>1995-05-24</Release_Date>
		<Runtime>127</Runtime>
	</row>
	<row>
		<Movie_ID>M15</Movie_ID>
		<Title>Some Like It Hot</Title>
		<Director>Billy Wilder</Director>
		<Writer>Billy Wilder, I.A.L. Diamond</Writer>
		<Genre>Comedy</Genre>
		<Release_Date>1948-03-29</Release_Date>
		<Runtime>120</Runtime>
	</row>
</movie>
