=== davidqian91/startfromhere/database/hw4/review.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xs:element name="review">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="row" minOccurs ="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Review_ID" type="xs:string"/>
                            <xs:element name="Movie_ID" type="xs:string"/>
                            <xs:element name="Rating">
                                <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                        <xs:minInclusive value="1"/>
                                        <xs:maxInclusive value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="Review_Date" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== davidqian91/startfromhere/database/hw4/review.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<review xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="review.xsd">
	<row>
		<Review_ID>U1</Review_ID>
		<Movie_ID>M1</Movie_ID>
		<Rating>10</Rating>
		<Review_Date>2008-11-28</Review_Date>
	</row>
	<row>
		<Review_ID>U2</Review_ID>
		<Movie_ID>M1</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2001-08-03</Review_Date>
	</row>
	<row>
		<Review_ID>U3</Review_ID>
		<Movie_ID>M1</Movie_ID>
		<Rating>9</Rating>
		<Review_Date>1999-03-25</Review_Date>
	</row>
	<row>
		<Review_ID>U4</Review_ID>
		<Movie_ID>M2</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2005-11-21</Review_Date>
	</row>
	<row>
		<Review_ID>U5</Review_ID>
		<Movie_ID>M2</Movie_ID>
		<Rating>7</Rating>
		<Review_Date>2010-10-24</Review_Date>
	</row>
	<row>
		<Review_ID>U6</Review_ID>
		<Movie_ID>M3</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2009-05-20</Review_Date>
	</row>
	<row>
		<Review_ID>U7</Review_ID>
		<Movie_ID>M4</Movie_ID>
		<Rating>9</Rating>
		<Review_Date>2002-09-01</Review_Date>
	</row>
	<row>
		<Review_ID>U8</Review_ID>
		<Movie_ID>M4</Movie_ID>
		<Rating>7</Rating>
		<Review_Date>2006-09-07</Review_Date>
	</row>
	<row>
		<Review_ID>U9</Review_ID>
		<Movie_ID>M4</Movie_ID>
		<Rating>10</Rating>
		<Review_Date>1998-08-02</Review_Date>
	</row>
	<row>
		<Review_ID>U10</Review_ID>
		<Movie_ID>M4</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2004-12-10</Review_Date>
	</row>
	<row>
		<Review_ID>U11</Review_ID>
		<Movie_ID>M4</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2005-09-30</Review_Date>
	</row>
	<row>
		<Review_ID>U12</Review_ID>
		<Movie_ID>M5</Movie_ID>
		<Rating>9</Rating>
		<Review_Date>2002-03-05</Review_Date>
	</row>
	<row>
		<Review_ID>U13</Review_ID>
		<Movie_ID>M5</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2001-05-16</Review_Date>
	</row>
	<row>
		<Review_ID>U14</Review_ID>
		<Movie_ID>M6</Movie_ID>
		<Rating>9</Rating>
		<Review_Date>2013-08-11</Review_Date>
	</row>
	<row>
		<Review_ID>U15</Review_ID>
		<Movie_ID>M6</Movie_ID>
		<Rating>9</Rating>
		<Review_Date>2012-10-14</Review_Date>
	</row>
	<row>
		<Review_ID>U16</Review_ID>
		<Movie_ID>M6</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2014-06-20</Review_Date>
	</row>
	<row>
		<Review_ID>U17</Review_ID>
		<Movie_ID>M7</Movie_ID>
		<Rating>6</Rating>
		<Review_Date>2006-10-06</Review_Date>
	</row>
	<row>
		<Review_ID>U18</Review_ID>
		<Movie_ID>M8</Movie_ID>
		<Rating>9</Rating>
		<Review_Date>2009-07-04</Review_Date>
	</row>
	<row>
		<Review_ID>U19</Review_ID>
		<Movie_ID>M8</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2009-02-24</Review_Date>
	</row>
	<row>
		<Review_ID>U20</Review_ID>
		<Movie_ID>M8</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2010-06-29</Review_Date>
	</row>
	<row>
		<Review_ID>U1</Review_ID>
		<Movie_ID>M9</Movie_ID>
		<Rating>7</Rating>
		<Review_Date>2009-05-16</Review_Date>
	</row>
	<row>
		<Review_ID>U2</Review_ID>
		<Movie_ID>M9</Movie_ID>
		<Rating>7</Rating>
		<Review_Date>2008-06-21</Review_Date>
	</row>
	<row>
		<Review_ID>U3</Review_ID>
		<Movie_ID>M10</Movie_ID>
		<Rating>9</Rating>
		<Review_Date>2006-06-14</Review_Date>
	</row>
	<row>
		<Review_ID>U4</Review_ID>
		<Movie_ID>M11</Movie_ID>
		<Rating>10</Rating>
		<Review_Date>2012-07-01</Review_Date>
	</row>
	<row>
		<Review_ID>U5</Review_ID>
		<Movie_ID>M11</Movie_ID>
		<Rating>6</Rating>
		<Review_Date>2010-09-19</Review_Date>
	</row>
	<row>
		<Review_ID>U6</Review_ID>
		<Movie_ID>M11</Movie_ID>
		<Rating>7</Rating>
		<Review_Date>2011-09-25</Review_Date>
	</row>
	<row>
		<Review_ID>U7</Review_ID>
		<Movie_ID>M11</Movie_ID>
		<Rating>7</Rating>
		<Review_Date>2012-04-04</Review_Date>
	</row>
	<row>
		<Review_ID>U8</Review_ID>
		<Movie_ID>M12</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2015-01-25</Review_Date>
	</row>
	<row>
		<Review_ID>U9</Review_ID>
		<Movie_ID>M12</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2013-10-14</Review_Date>
	</row>
	<row>
		<Review_ID>U10</Review_ID>
		<Movie_ID>M13</Movie_ID>
		<Rating>9</Rating>
		<Review_Date>2005-02-23</Review_Date>
	</row>
	<row>
		<Review_ID>U1</Review_ID>
		<Movie_ID>M14</Movie_ID>
		<Rating>7</Rating>
		<Review_Date>2008-10-04</Review_Date>
	</row>
	<row>
		<Review_ID>U2</Review_ID>
		<Movie_ID>M14</Movie_ID>
		<Rating>9</Rating>
		<Review_Date>2008-09-26</Review_Date>
	</row>
	<row>
		<Review_ID>U3</Review_ID>
		<Movie_ID>M14</Movie_ID>
		<Rating>7</Rating>
		<Review_Date>2015-03-15</Review_Date>
	</row>
	<row>
		<Review_ID>U1</Review_ID>
		<Movie_ID>M15</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2015-03-10</Review_Date>
	</row>
	<row>
		<Review_ID>U2</Review_ID>
		<Movie_ID>M15</Movie_ID>
		<Rating>8</Rating>
		<Review_Date>2015-03-10</Review_Date>
	</row>
</review>
