=== davidqian91/startfromhere/database/hw4/reviewer.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified"> 
    <xs:element name="reviewer">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="row" minOccurs ="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Reviewer_ID" type="xs:string"/>
                            <xs:element name="Reviewer_Name" type="xs:string"/>
                            <xs:element name="Reviewer_DOB" type="xs:date"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== davidqian91/startfromhere/database/hw4/reviewer.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<reviewer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="reviewer.xsd">
	<row>
		<Reviewer_ID>U1</Reviewer_ID>
		<Reviewer_Name>Wesley S. Walker</Reviewer_Name>
		<Reviewer_DOB>1990-02-08</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U2</Reviewer_ID>
		<Reviewer_Name>Justin M</Reviewer_Name>
		<Reviewer_DOB>1985-10-02</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U3</Reviewer_ID>
		<Reviewer_Name>Si Cole</Reviewer_Name>
		<Reviewer_DOB>1991-10-10</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U4</Reviewer_ID>
		<Reviewer_Name>Tim Cox</Reviewer_Name>
		<Reviewer_DOB>1980-03-25</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U5</Reviewer_ID>
		<Reviewer_Name>Thomas McFadden</Reviewer_Name>
		<Reviewer_DOB>1983-07-21</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U6</Reviewer_ID>
		<Reviewer_Name>Dan Grant</Reviewer_Name>
		<Reviewer_DOB>1981-04-10</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U7</Reviewer_ID>
		<Reviewer_Name>Thomas Peluso</Reviewer_Name>
		<Reviewer_DOB>1970-09-24</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U8</Reviewer_ID>
		<Reviewer_Name>Dennis Littrell</Reviewer_Name>
		<Reviewer_DOB>1986-05-20</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U9</Reviewer_ID>
		<Reviewer_Name>Theo Robertson</Reviewer_Name>
		<Reviewer_DOB>1981-10-12</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U10</Reviewer_ID>
		<Reviewer_Name>Robert Hoffman</Reviewer_Name>
		<Reviewer_DOB>1986-09-11</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U11</Reviewer_ID>
		<Reviewer_Name>Bernard Sandberg</Reviewer_Name>
		<Reviewer_DOB>1982-12-20</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U12</Reviewer_ID>
		<Reviewer_Name>Lucy Webb</Reviewer_Name>
		<Reviewer_DOB>1988-05-21</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U13</Reviewer_ID>
		<Reviewer_Name>David Johnson</Reviewer_Name>
		<Reviewer_DOB>1981-10-02</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U14</Reviewer_ID>
		<Reviewer_Name>Howlin Wolf</Reviewer_Name>
		<Reviewer_DOB>1987-03-08</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U15</Reviewer_ID>
		<Reviewer_Name>Sandeep Manudhane</Reviewer_Name>
		<Reviewer_DOB>1971-06-15</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U16</Reviewer_ID>
		<Reviewer_Name>Peter Dourountzis</Reviewer_Name>
		<Reviewer_DOB>1973-12-24</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U17</Reviewer_ID>
		<Reviewer_Name>Chris Dowling</Reviewer_Name>
		<Reviewer_DOB>1982-10-21</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U18</Reviewer_ID>
		<Reviewer_Name>Gabriela Barocio</Reviewer_Name>
		<Reviewer_DOB>1984-10-07</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U19</Reviewer_ID>
		<Reviewer_Name>Sigurd Vilstrup</Reviewer_Name>
		<Reviewer_DOB>1974-06-13</Reviewer_DOB>
	</row>
	<row>
		<Reviewer_ID>U20</Reviewer_ID>
		<Reviewer_Name>Sam Thomson</Reviewer_Name>
		<Reviewer_DOB>1982-09-22</Reviewer_DOB>
	</row>
</reviewer>
